use_frameworks!

platform :ios, '10.0'

target 'CloudreveVLCPlayer_Example' do
  pod 'CloudreveVLCPlayer', :path => '../'

  target 'CloudreveVLCPlayer_Tests' do
    inherit! :search_paths

    pod 'MobileVLCKit', '3.6.0b5'
    pod 'VLCMediaLibraryKit', '0.11.0b2'
    pod 'Masonry'
    
  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end

